apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tradingview-duckdns-certificate
  namespace: tv
spec:
  dnsNames:
  - 'tradingview.kdoan.duckdns.org'
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
  secretName: tradingview-duckdns-tls
