apiVersion: v1
kind: Service
metadata:
  name: tradingview-webhook-service
  namespace: tv
spec:
  selector:
    app: tradingview-webhook
  ports:
    - name: api
      protocol: TCP
      port: 8000
      targetPort: api